config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users
    root 'articles#index'

    resources :articles do # para facilitar o link de rotas
      resources :comments, only: %i[create destroy]
    end

    resources :categories, except: [:show]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article
    before_action :authenticate_user!

    def create
        @article.comments.create(comment_params.to_h.merge!({user_id: current_user.id}))
        redirect_to article_path(@article), notice: 'Comment successfully created.'
    end

    def destroy
        comment = @article.comments.find(params[id])
        authorize comment

        comment.destroy
        redirect_to article_path(@article), notice: 'Comment successfully destroy'
    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end

    def set_article
        @article = Article.find(params[:article_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
 
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= month_day_comma_year(comment.created_at)%></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= t 'comments.index.commenter'%> : <%= sub_masked_email (comment.user.email) %></h6>
    <p class="card-text"><%= comment.body %></p>
    <%= link_to t('comments.index.destroy.title'), article_comment_path(@article,comment), method: :delete, data: {confirm: t('comments.index.destroy.confirm')}, class: 'btn btn-danger' if policy(comment).destroy? %>
  </div>
</div>
  

app/views/comments/_form.html.erb
<%= simple_form_for [@article, @article.comments.build] do |f| %>
  <div class="form-inputs">
    <%= f.input :body, input_html: {rows:5}%>
  </div>
  <div class = "form-action">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<%end%>