config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users
    root 'articles#index'

    resources :articles do # para facilitar o link de rotas
      resources :comments, only: %i[create destroy]
    end

    resources :categories, except: [:show]
  end
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 3}
    validates :body, presence: true, length: {minimum: 10}
    paginates_per 10
    scope :desc_order, -> {order(created_at: :desc)}
    scope :without_highlights, -> (ids) {where("id NOT IN (#{ids})") if ids.present? }
    scope :filter_by_category, -> (category) {where category_id: category if category.present?}
    scope :filter_by_archive, lambda {|month_year|
        if month_year
            date = Date.strptime(month_year, '%B %Y')
            where created_at: date.beginning_of_month..date.end_of_month.next_day #fim do mes mais 1
        end
    }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Paginable
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[show edit update destroy]
  before_action :set_categories, only: %i[index new create edit update]

  def index
    @archives = Article.group_by_month(:created_at, format: "%b %Y", locale: :en).count

    category = @categories.find { |c| c.name == params[:category] } if params[:category].present?
    month_year = @archives.find { |m| m[0] == params[:month_year] }&.first if params[:month_year].present?

    @highlights = Article.includes(:category, :user)
                         .filter_by_category(category)
                         .filter_by_archive(month_year)
                         .desc_order
                         .first(3)

    
    highlights_ids = @highlights.pluck(:id)
                                .join(',')
    
    @articles = Article.includes(:category, :user)
                       .without_highlights(highlights_ids)
                       .filter_by_category(category)
                       .filter_by_archive(month_year)
                       .desc_order.page(current_page)

    
  end

  def show 
    @article = Article.includes(comments: :user).find(params[:id])
    authorize @article
   end

  def new
    @article= current_user.articles.new 
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article, notice: t('articles.create.success')
    else
      render :new
    end
  end

  def edit; end

  def update 
    if @article.update(article_params)
      redirect_to @article, notice: t('articles.update.success')
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, notice: t('articles.destroy.success')
  end

  private 

  def article_params
    params.require(:article)
          .permit(:title, :body, :category_id)
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end

  def set_categories
    @categories = Category.sorted
  end
end
  
  

app/helpers/articles_helper.rb
module ArticlesHelper
    def month_day_comma_year(value)
        l(value, format: '%B %e, %Y').capitalize # documentação para data
    end
end

app/views/articles/_about.html.erb
<div class="p-4 mb-3 bg-light rounded">
  <h4 class="fst-italic"><%= t '.title' %></h4>
  <p class="mb-0"><%= t '.description' %> </p>
</div>

app/views/articles/_archives.html.erb
<div class="p-4">
  <h4 class="fst-italic"><%= t 'articles.archives' %></h4>
  <ol class="list-unstyled mb-0">
    <% @archives.each do |month_year, count| %>
    <li>
      <%= link_to "#{month_year(month_year)} #{count}", articles_path(month_year: month_year),
            class: "p-2 link-secondary #{'filter-active' if month_year == params[:category]}" %>
    </li>
    <%end%>
  </ol>
</div>

app/views/articles/_article.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%=article.title%></h2>
  <%# esta em help %>
  <p class="blog-post-meta">
    <%= render "article_detail", article: article %>
  </p>
  <p><%= link_to t('articles.continue_reading'), article, class: 'btn-btn-link'%></p>
  <%= link_to 'Edit', edit_article_path(article), 
      class: 'btn btn-primary' if policy(article).update? %>
  <%= link_to 'Destroy', article_path(article), method: :delete, data: {confirm: 'Are yoy sure?'}, 
      class: 'btn btn-danger' if policy(article).destroy? %>
</article>

app/views/articles/_article_detail.html.erb
<%= month_day_comma_year(article.created_at) %> <%= t 'app.word.by'%>
<%= sub_masked_email(article.user.email) %> <%= t 'app.word.in'%>
<%= article.category.name%>

app/views/articles/_elsewhere.html.erb
<div class="p-4">
  <h4 class="fst-italic"><%= t 'articles.elsewhere'%></h4>
  <ol class="list-unstyled">
    <li><a href="http://github.com/vinicioboniatti" target="_blank">Git Hub</a></li>
    <li><a href="https://www.linkedin.com/in/vinicioboniatti/" target="_blank" >Linkedin</a></li>
  </ol>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, input_html: { rows:10 } %>
    <%= f.association :category, collection: @categories, prompt: t('articles.form.choose_category') %>
  </div>
  <div class="form-inputs">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to t('articles.form.back'), root_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/articles/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 fst-italic"><%= article.title %></h1>
    <p class="lead my-3"><%= truncate(article.body, lenght: 100) %></p>
    <p class="lead mb-0">
    <%= link_to t('articles.continue_reading'), article, class: "text-white fw-bold"%>
    </p>
  </div>
</div>

app/views/articles/_medium_featured.html.erb
<div class="col-md-6">
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary">
        <%= article.category.name%>
      </strong>

      <h3 class="mb-0"><%= article.title %></h3>

      <div class="mb-1 text-muted">
      <%= render "article_detail", article: article %>
      </div>

      <p class="card-text mb-auto"><%= truncate(article.body, lenght: 100) %></p>
      
      <%= link_to t('articles.continue_reading'), article, class: "stretched-link"%>
    </div>

    <div class="col-auto d-none d-lg-block">
      <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
    </div>
  </div>
</div>

app/views/articles/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">
  <%= link_to_next_page @articles, t('app.pagination.older'), class: 'btn btn-outline-primary' %>
  <%= link_to_previous_page @articles, t('app.pagination.newer'), class: 'btn btn-outline-primary' %>
</nav>

app/views/articles/_right_side.html.erb
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <%= render 'about'%>
    <%= render 'archives'%>
    <%= render 'elsewhere' %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1><%= t ('articles.update.title')%></h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<%= render_if @highlights[0].present?, 'longer_featured', article: @highlights[0] %>
<div class="row mb-2">
  <%= render_if @highlights[1].present?, 'medium_featured',article: @highlights[1] %>
  <%= render_if @highlights[2].present?, 'medium_featured',article: @highlights[2] %>
</div>
<div class="row g-5">
  <div class="col-md-8">
    <h3 class="pb-4 mb-4 fst-italic border-bottom">
      <%= t '.subtitle'%>
    </h3>
    <p><%= link_to t('.new_article'), new_article_path, 
    class: 'btn btn-success' if user_signed_in? %></p>
    <%# link para cria um novo artigo%>
    <%= render @articles %>
    <%= render 'pagination' %>
  </div>
  <%= render 'right_side'%>
</div>
<%= content_for :category_filter do %>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <% @categories.each do |category| %>
        <%= link_to category.name, articles_path(category: category.name),
            class: "p-2 link-secondary #{'filter-active' if category.name.to_s == params[:category]}" %>
      <%end%>
    </nav>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1><%= t'articles.new.title' %></h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%=@article.title%></h2>
  <%# esta em help %>
  <p class="blog-post-meta">
    <%= render "article_detail", article: @article %>
  </p>
  <p><%= @article.body %></p>
  <%= link_to t('articles.show.edit'), edit_article_path(@article),      
          class: 'btn btn-primary' if policy(@article).update? %>
  <%= link_to t('articles.show.destroy'), article_path(@article), method: :delete, data: {confirm: t('articles.destroy.confirm')}, 
          class: 'btn btn-danger' if policy(@article).destroy? %>
  <%= link_to t('articles.show.back'), root_path, class: 'btn btn-secondary' %>
  <h2 class="mt-3"><%= t('articles.show.comments') %></h2>
  <%= render @article.comments %>
  <h2><%= t('articles.show.add_comment') %></h2>
  <% if policy(:comment).create?%>
    <%= render 'comments/form'%>
  <% else %>
    <%= t('articles.show.login_create_comment') %>
  <%end%>
</article>