config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users
    root 'articles#index'

    resources :articles do # para facilitar o link de rotas
      resources :comments, only: %i[create destroy]
    end

    resources :categories, except: [:show]
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error
    validates :name, 
              presence: true, 
              length: {minimum: 3},
              uniqueness: {case_sensitive: false }
              
    scope :sorted, -> {order(:name)}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = policy_scope(Category.sorted)
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: t('categories.new.creat.sucess') }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: t('categories.new.edit.sucess')}
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: t('categories.new.destroy.sucess')}
        format.json { head :no_content }
      end
    else
      redirect_to categories_url, alert: @category.errors.messages[:base][0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      authorize @category
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('categories.new.title') %></h1>

<%= render 'form', category: @category %>

<%= link_to t('categories.new.back.title'), categories_path %>

app/views/categories/index.html.erb
<h1><%= t Category.model_name.human(count: 2) %></h1>

<p><%= link_to t('categories.new.title'), new_category_path, 
  class: 'btn btn-primary' if policy(:category).new?  %></p>

<table class="table table-striped-columns table-hover table-bordered">
  <thead>
    <tr>
      <th><%= t(Category.human_attribute_name('name')) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody> 
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to t('categories.new.edit.title'), edit_category_path(category) if policy(category).edit? %></td>
        <td><%= link_to t('categories.new.destroy.title'), category, method: :delete, data: { confirm: t('categories.new.destroy.confirm') } if policy(category).destroy? %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/categories/new.html.erb
<h1><%= t('categories.new.title') %></h1>

<%= render 'form', category: @category %>

<%= link_to t('categories.new.back.title'), categories_path %>

app/views/categories/show.html.erb
<p>
  <strong><%= t('categories.new.title')%></strong>
  <%= @category.name %>
</p>
<%= link_to t('categories.new.edit.title'), edit_category_path(@category) %> |
<%= link_to t('categories.new.back.title'), categories_path %>